services:
  client_prod:
    image: baptcave/mes-films-favoris-prod-client
    container_name: mff-prod-client
    ports:
      - "3000:3000"
    networks:
      - prod-network

  server_prod:
    image: baptcave/mes-films-favoris-prod-server
    container_name: mff-prod-server
    depends_on:
      - db_prod
    environment:
      APP_PORT: 8000
      FRONTEND_URL: https://mesfilmsfavoris.duckdns.org
      JWT_SECRET: baptou47
      DB_HOST: db_prod
      DB_PORT: 3306
      DB_USER: baptiste
      DB_PASSWORD: CarniBAL--18/
      DB_NAME: films
      CORS_ALLOWED_ORIGINS: https://mesfilmsfavoris.duckdns.org,https://api.mesfilmsfavoris.duckdns.org
    ports:
      - "8000:8000"
    networks:
      - prod-network

  db_prod:
    image: mysql:8.3
    container_name: mff-prod-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpsd
      MYSQL_USER: baptiste
      MYSQL_PASSWORD: CarniBAL--18/
      MYSQL_DATABASE: films
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - db-data-prod:/var/lib/mysql
    networks:
      - prod-network

networks:
  prod-network:
    driver: bridge

volumes:
  db-data-prod:
