services:
  db_test:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: baptiste
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: films
    tmpfs: /var/lib/mysql
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysql -h 127.0.0.1 -uroot -proot"]
      interval: 30s
      timeout: 20s
      retries: 10

  client_test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      VITE_BACKEND_URL: http://server_test:8000
      VITE_API_KEY: d1195e56de3a08fa85ce12980ecb94b4
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src/:/app/src/
      - ./frontend/public/:/app/public/
      - ./frontend/cypress/:/app/cypress/
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/declaration.d.ts:/app/declaration.d.ts

  server_test:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      db_test:
        condition: service_healthy
    environment:
      APP_PORT: 8000
      FRONTEND_URL: http://client_test
      JWT_SECRET: xXxXxXxX
      DB_HOST: db_test
      DB_PORT: 3306
      DB_USER: baptiste
      DB_PASSWORD: password
      DB_NAME: films
      CORS_ALLOWED_ORIGINS: http://client_test:3000,http://server_test:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src/:/app/src/
      - ./backend/public/:/app/public/
      - ./backend/tsconfig.json:/app/tsconfig.json
      - ./backend/index.ts:/app/index.ts
      - ./backend/populateDB.ts:/app/populateDB.ts
      - ./backend/db-fixtures.sql:/app/db-fixtures.sql

  cypress:
    image: cypress/included:13.6.3
    working_dir: /e2e
    volumes:
      - ./frontend/:/e2e
    depends_on:
      client_test:
        condition: service_started
      server_test:
        condition: service_started
    environment:
      CYPRESS_baseUrl: http://client_test:3000
