-- MySQL Script generated by MySQL Workbench
-- Mon Apr  3 13:45:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema films
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `films` ;

-- -----------------------------------------------------
-- Schema films
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `films` DEFAULT CHARACTER SET utf8 ;
USE `films` ;

-- -----------------------------------------------------
-- Table `films`.`movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `films`.`movie` ;

CREATE TABLE IF NOT EXISTS `films`.`movie` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title_fr` VARCHAR(150) NOT NULL,
  `length` INT(11) NOT NULL,
  `year` INT(11) NOT NULL,
  `director` VARCHAR(80) NOT NULL,
  `cast` TEXT NOT NULL,
  `imdb_note` DECIMAL(2,0) NOT NULL,
  `poster` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `films`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `films`.`user` ;

CREATE TABLE IF NOT EXISTS `films`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(80) NOT NULL,
  `lastname` VARCHAR(80) NOT NULL,
  `age` INT(11) NULL DEFAULT NULL,
  `city` VARCHAR(80) NULL DEFAULT NULL,
  `country` VARCHAR(80) NOT NULL,
  `mail` VARCHAR(80) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

LOCK TABLES `user` WRITE;
/*!40000 ALTER TABLE `user` DISABLE KEYS */;
INSERT INTO `user` VALUES 
(1, "Benoit", "Admin", 30, "Lyon", "France", "benoit@gmail.com", "$argon2id$v=19$m=524288,t=5,p=1$JUha8fciF0z+bSquR0PkoQ$znb6z7q7UtBtlljS9cxVTZgvVTlJ4bEg9gl4PCaVgWM");
/*!40000 ALTER TABLE `user` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `films`.`user_has_movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `films`.`user_has_movies` ;

CREATE TABLE IF NOT EXISTS `films`.`user_has_movies` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date_seen` DATE NULL DEFAULT NULL,
  `mode_seen` VARCHAR(45) NULL DEFAULT NULL,
  `my_note` INT(11) NOT NULL,
  `comment` TEXT NOT NULL,
  `id_user` INT(11) NOT NULL,
  `id_movie` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `id_movie_idx` (`id_movie` ASC) VISIBLE,
  CONSTRAINT `id_movie`
    FOREIGN KEY (`id_movie`)
    REFERENCES `films`.`movie` (`id`),
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `films`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
