name: component-testing

on:
  pull_request:
  workflow_call:

jobs:
  test-components:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install npm and deps
        run: cd frontend && npm i
      - name: Go to frontend and run testing
        run: cd frontend && npm run comp-test:run
