name: Compile and push client and server to prod

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push-server-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:backend"
          file: "Dockerfile.prod"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mes-films-favoris-prod-server

  build-and-push-client-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:frontend"
          file: "Dockerfile.prod"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mes-films-favoris-prod-client
          build-args: |
            VITE_BACKEND_URL=https://api.mesfilmsfavoris.duckdns.org
            VITE_API_KEY=${{ secrets.VITE_API_KEY }}

  notify:
    needs:
      - build-and-push-server-prod
      - build-and-push-client-prod
    runs-on: ubuntu-latest
    steps:
      - name: Call VPS webhook to update prod
        uses: wei/curl@master
        with:
          args: https://ops.mesfilmsfavoris.duckdns.org/hooks/update-prod
