name: e2e-testing

on:
  pull_request:
    branches:
      - dev
  workflow_call:

jobs:
  test-End-to-End:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Cypress e2e run
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          browser: chrome
